/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Viresh;

import javax.swing.ImageIcon;


/**
 *
 * @author Viresh
 */
public class Instructie extends javax.swing.JFrame {
    /**
     * Creates new form Instructie
     */
    public Instructie() {
        initComponents();
         this.setIconImage(new ImageIcon(getClass().getResource("sms_logo.png")).getImage());
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtinstructie = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Instructies");
        setResizable(false);

        txtinstructie.setColumns(20);
        txtinstructie.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtinstructie.setRows(5);
        txtinstructie.setText("De EBS verbruikerscalculator stelt u in staat aan de hand van uw verbruik een \nindicatie te krijgen van uw stroomrekening.\n\nStap 1.\nOp uw elektriciteitsrekening staat linksboven aangegeven welke fase aansluiting u heeft.\nKlik uw fase aansluiting aan.(Fase1,Fase2,Fase3)\nStap 2.\nNeem een meterstand van de vorige maand en een huidige.\nVul de vakjes \"Beginstand\" en \"Eindstand\" in.\nStap 3.\nKlik op “Berekenen”.");
        txtinstructie.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtinstructiePropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(txtinstructie);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtinstructiePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtinstructiePropertyChange
        // TODO add your handling code here:
        txtinstructie.setEditable(false);                
    }//GEN-LAST:event_txtinstructiePropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Instructie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Instructie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Instructie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Instructie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Instructie().setVisible(true);
            }
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtinstructie;
    // End of variables declaration//GEN-END:variables
}
