/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Viresh;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
/**
 *
 * @author Viresh
 */
public class Verbruikerscalculator extends javax.swing.JFrame {

    /**
     * Creates new form EBScal
     */
    public Verbruikerscalculator() {
        initComponents();   
        this.setIconImage(new ImageIcon(getClass().getResource("sms_logo.png")).getImage());
        this.setLocationRelativeTo(null);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBeginstand = new javax.swing.JLabel();
        lblEindstand = new javax.swing.JLabel();
        lblVerbruik = new javax.swing.JLabel();
        txtBeginstand = new javax.swing.JTextField();
        txtEindstand = new javax.swing.JTextField();
        txtVerbruik = new javax.swing.JTextField();
        rbFase1 = new javax.swing.JRadioButton();
        rbFase2 = new javax.swing.JRadioButton();
        rbFase3 = new javax.swing.JRadioButton();
        txtSaldoa = new javax.swing.JTextField();
        txtSaldob = new javax.swing.JTextField();
        txtSaldoc = new javax.swing.JTextField();
        txtSaldod = new javax.swing.JTextField();
        txtSaldoe = new javax.swing.JTextField();
        txtSaldof = new javax.swing.JTextField();
        txtSaldog = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtResa = new javax.swing.JTextField();
        txtResb = new javax.swing.JTextField();
        txtResc = new javax.swing.JTextField();
        txtResd = new javax.swing.JTextField();
        txtRese = new javax.swing.JTextField();
        txtResf = new javax.swing.JTextField();
        txtResg = new javax.swing.JTextField();
        lblTotaal = new javax.swing.JLabel();
        lblFase = new javax.swing.JLabel();
        lblRekening = new javax.swing.JLabel();
        txtTotaal = new javax.swing.JTextField();
        txtFase = new javax.swing.JTextField();
        txtRekening = new javax.swing.JTextField();
        btnBereken = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btninstructie = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EBS Verbruikerscalculator");
        setBackground(new java.awt.Color(204, 204, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(600, 750));
        setResizable(false);

        lblBeginstand.setText("Beginstand");

        lblEindstand.setText("Eindstand");

        lblVerbruik.setText("Verbruik");

        txtBeginstand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBeginstandActionPerformed(evt);
            }
        });
        txtBeginstand.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBeginstandKeyTyped(evt);
            }
        });

        txtEindstand.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEindstandKeyTyped(evt);
            }
        });

        txtVerbruik.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtVerbruikPropertyChange(evt);
            }
        });

        rbFase1.setText("Fase 1");
        rbFase1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbFase1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFase1ActionPerformed(evt);
            }
        });

        rbFase2.setText("Fase 2");
        rbFase2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbFase2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFase2ActionPerformed(evt);
            }
        });

        rbFase3.setText("Fase 3");
        rbFase3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbFase3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFase3ActionPerformed(evt);
            }
        });

        txtSaldoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaldoaActionPerformed(evt);
            }
        });
        txtSaldoa.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtSaldoaPropertyChange(evt);
            }
        });

        txtSaldob.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtSaldobPropertyChange(evt);
            }
        });

        txtSaldoc.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtSaldocPropertyChange(evt);
            }
        });

        txtSaldod.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtSaldodPropertyChange(evt);
            }
        });

        txtSaldoe.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtSaldoePropertyChange(evt);
            }
        });

        txtSaldof.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtSaldofPropertyChange(evt);
            }
        });

        txtSaldog.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtSaldogPropertyChange(evt);
            }
        });

        jLabel1.setText("X 0.15");

        jLabel2.setText("X 0.27");

        jLabel3.setText("X 0.30");

        jLabel4.setText("X 0.33");

        jLabel5.setText("X 0.36");

        jLabel6.setText("X 0.37");

        jLabel7.setText("X 0.40");

        txtResa.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtResaPropertyChange(evt);
            }
        });

        txtResb.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtResbPropertyChange(evt);
            }
        });

        txtResc.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtRescPropertyChange(evt);
            }
        });

        txtResd.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtResdPropertyChange(evt);
            }
        });

        txtRese.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtResePropertyChange(evt);
            }
        });

        txtResf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResfActionPerformed(evt);
            }
        });
        txtResf.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtResfPropertyChange(evt);
            }
        });

        txtResg.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtResgPropertyChange(evt);
            }
        });

        lblTotaal.setText("Totaal");

        lblFase.setText("Abonnementskosten");

        lblRekening.setText("Uw rekening is:");

        txtTotaal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotaalActionPerformed(evt);
            }
        });
        txtTotaal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtTotaalPropertyChange(evt);
            }
        });

        txtFase.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtFasePropertyChange(evt);
            }
        });

        txtRekening.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtRekeningPropertyChange(evt);
            }
        });

        btnBereken.setText("Bereken");
        btnBereken.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBereken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBerekenActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Viresh/newpackage/logo.png"))); // NOI18N
        jLabel9.setPreferredSize(new java.awt.Dimension(390, 100));

        btninstructie.setText("Instructies");
        btninstructie.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btninstructie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninstructieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBeginstand, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblBeginstand, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEindstand, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(lblEindstand, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVerbruik, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblVerbruik, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbFase1)
                                .addGap(23, 23, 23)
                                .addComponent(rbFase2)
                                .addGap(13, 13, 13)
                                .addComponent(rbFase3))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtSaldoa)
                                        .addGap(35, 35, 35)
                                        .addComponent(jLabel1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtSaldob, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtSaldoc, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtSaldod, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtSaldoe, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtSaldof, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtSaldog, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtResg, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtResc, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtResa, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtResb, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtResd, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRese, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtResf, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTotaal)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTotaal, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblFase)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtFase, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblRekening, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtRekening, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBereken)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btninstructie)))))
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbFase1)
                    .addComponent(rbFase2)
                    .addComponent(rbFase3))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBeginstand)
                    .addComponent(lblEindstand)
                    .addComponent(lblVerbruik))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBeginstand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEindstand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVerbruik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSaldoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtResa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtResb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtResc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSaldob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSaldoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSaldod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txtResd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSaldoe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtRese, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtResf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSaldof, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtResg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtSaldog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotaal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotaal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFase))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRekening, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRekening))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btninstructie)
                    .addComponent(btnReset)
                    .addComponent(btnBereken))
                .addGap(47, 47, 47))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtResfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResfActionPerformed

    private void btnBerekenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBerekenActionPerformed
        // TODO add your handling code here:
        
        float beginstand;
        float eindstand;
        float verbruik;
        double limit= 150;
        float res2;
        float saldo2;
        double totaal1;
        float fase;
        float uitkomst;
            
                
               
                
                

        beginstand = Float.parseFloat(this.txtBeginstand.getText());
        eindstand = Float.parseFloat(this.txtEindstand.getText());
        verbruik = eindstand - beginstand;
        this.txtVerbruik.setText(String.valueOf(verbruik));
       
        float totaal;
        float saldo1;
        float res1;
         
      

        if(verbruik <= limit){
        this.txtSaldoa.setText(String.valueOf(verbruik));
        res1=(float) (verbruik * 0.15);
        this.txtResa.setText(String.valueOf(res1));
        totaal=res1;
        this.txtTotaal.setText(String.valueOf(totaal));
          

        }
            else if (verbruik > limit){
            float res3;

        this.txtSaldob.setText(String.valueOf(limit));
             res2 = (float) (limit*0.27);
                    this.txtResb.setText(String.valueOf(res2));
                     saldo1 =(float) (verbruik - limit);
                              
                            res3=(float) (saldo1 * 0.30);
                            this.txtResc.setText(String.valueOf(res3));  
                                totaal=res2+res3;
                                    this.txtTotaal.setText(String.valueOf(totaal));

                                        saldo2 =(float) (saldo1 - limit);

                    
                 
                        float saldo3;
                        if(saldo1 < limit){
                             this.txtSaldoc.setText(String.valueOf(saldo1));
                                    res3=(float) (saldo1 * 0.30);
                                        this.txtResc.setText(String.valueOf(res3));  
                                             totaal=res2+res3;
                                                 this.txtTotaal.setText(String.valueOf(totaal));

                            }
                                else  if(saldo1 >= limit){
                                        this.txtSaldoc.setText(String.valueOf(limit));
                                             res3=(float) (limit * 0.30);
                                                this.txtResc.setText(String.valueOf(res3)); 
                                                   saldo3=(float) (saldo2 - limit);
               
               
               
                        float res4;
                        float saldo4;
                         if(saldo2 < limit){
                            this.txtSaldod.setText(String.valueOf(saldo2));
                            res4=(float) (saldo2 * 0.33);
                            this.txtResd.setText(String.valueOf(res4));  
                            totaal=res2+res3+res4;
                                 this.txtTotaal.setText(String.valueOf(totaal));
                            }
                                else  if(saldo2 >= limit){
                                     this.txtSaldod.setText(String.valueOf(limit));
                                         res4=(float) (limit * 0.33);
                                                this.txtResd.setText(String.valueOf(res4));
                                                    saldo4=(float) (saldo3 - limit);
                
                
                
                         float res5;
                         float saldo5;
                         if(saldo3 < limit){
                             this.txtSaldoe.setText(String.valueOf(saldo3));
                                 res5=(float) (saldo3 * 0.36);
                                    this.txtRese.setText(String.valueOf(res5));
                                         totaal=res2+res3+res4+res5;
                                          this.txtTotaal.setText(String.valueOf(totaal));
                                             }
                                                 else  if(saldo3 >= limit){
                                                    this.txtSaldoe.setText(String.valueOf(limit));
                                                    res5=(float) (limit * 0.36);
                                                    this.txtRese.setText(String.valueOf(res5));
                                                    saldo5=(float) (saldo4 - limit);
                
               
                
                                float res6;
                                float saldo6;
                                    if(saldo4 < limit){
                                        this.txtSaldof.setText(String.valueOf(saldo4));
                                            res6=(float) (saldo4 * 0.37);
                                           this.txtResf.setText(String.valueOf(res6));
                                            totaal=res2+res3+res4+res5+res6;
                                            this.txtTotaal.setText(String.valueOf(totaal));
                                                   }
                                                     else  if(saldo4 >= limit){
                                                            this.txtSaldof.setText(String.valueOf(limit));
                                                                 res6=(float) (limit * 0.37);
                                                                    this.txtResf.setText(String.valueOf(res6));
                                                                        saldo6=(float) (saldo5 - limit);
                
               
                
                float res7;
                float laatste = 800;
                float fr = verbruik-laatste;
                if(laatste < verbruik){
                this.txtSaldog.setText(String.valueOf(fr));
                res7=(float) (fr * 0.40);
                                    this.txtResg.setText(String.valueOf(res7));
                                        totaal=res2+res3+res4+res5+res6+res7;
                                             this.txtTotaal.setText(String.valueOf(totaal));
                        getContentPane().setBackground(new Color(0 , 204, 0));
                        }
                                                     }
                        
                        
                                                 }
                                }
                                }
            }
        
               fase = (float) Double.parseDouble(txtFase.getText());
               totaal = (float)   Double.parseDouble(txtTotaal.getText());
               uitkomst =totaal+fase;
               this.txtRekening.setText("SRD "+String.valueOf(uitkomst));
    }                                        

    private void Fase1RadActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
      if(rbFase1.isSelected()){
            rbFase2.setSelected(false);
            rbFase3.setSelected(false);
            double fase;
            fase =10.85;
            this.txtFase.setText(String.valueOf(fase));}
    }                                        

    private void Fase2RadActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
         if(rbFase2.isSelected()){
            rbFase3.setSelected(false);
            rbFase1.setSelected(false);
            double fase;
            fase =16.50;
            this.txtFase.setText(String.valueOf(fase));

        }
    }                                        

    private void Fase3RadActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        if(rbFase3.isSelected()){
            rbFase2.setSelected(false);
            rbFase3.setSelected(false);
            double fase;
            fase =18.25;
            this.txtFase.setText(String.valueOf(fase));

        }
    }                                        

    private void BtnResetActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        this.txtSaldoa.setText("");
            this.txtSaldob.setText("");
                this.txtSaldoc.setText("");
                    this.txtSaldod.setText("");
                        this.txtSaldoe.setText("");
                            this.txtSaldof.setText("");
                                this.txtSaldog.setText("");
                                    
        this.txtResa.setText("");
            this.txtResb.setText("");
                this.txtResc.setText("");
                    this.txtResd.setText("");
                        this.txtRese.setText("");
                            this.txtResf.setText("");
                                this.txtResg.setText("");
                                
        this.txtBeginstand.setText("");
            this.txtEindstand.setText("");
                this.txtVerbruik.setText("");
        
        this.txtTotaal.setText("");
            this.txtFase.setText("");
                this.txtRekening.setText("");
                
        rbFase1.setSelected(false);
            rbFase2.setSelected(false);
                rbFase3.setSelected(false);
        
    }//GEN-LAST:event_btnBerekenActionPerformed

    private void rbFase1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFase1ActionPerformed
        // TODO add your handling code here:
     if(rbFase1.isSelected()){
          rbFase2.setSelected(false);
          rbFase3.setSelected(false);
            double fase;
            fase =10.85;
            this.txtFase.setText(String.valueOf(fase));}
    
                                           
    }//GEN-LAST:event_rbFase1ActionPerformed

    private void rbFase2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFase2ActionPerformed
        // TODO add your handling code here:
        if(rbFase2.isSelected()){
            rbFase1.setSelected(false);
            rbFase3.setSelected(false);
            double fase;
            fase =16.50;
            this.txtFase.setText(String.valueOf(fase));
         }
    }//GEN-LAST:event_rbFase2ActionPerformed

    private void rbFase3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFase3ActionPerformed
        // TODO add your handling code here:
         if(rbFase3.isSelected()){
            rbFase1.setSelected(false);
            rbFase2.setSelected(false);
            double fase;
            fase =18.25;
            this.txtFase.setText(String.valueOf(fase));

        }
    }//GEN-LAST:event_rbFase3ActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        
        this.txtBeginstand.setText("");
            this.txtEindstand.setText("");
                this.txtVerbruik.setText("");
        
        this.txtTotaal.setText("");
            this.txtFase.setText("");
                this.txtRekening.setText("");
        
                
                this.txtSaldoa.setText("");
            this.txtSaldob.setText("");
                this.txtSaldoc.setText("");
                    this.txtSaldod.setText("");
                        this.txtSaldoe.setText("");
                            this.txtSaldof.setText("");
                                this.txtSaldog.setText("");
                                    
        this.txtResa.setText("");
            this.txtResb.setText("");
                this.txtResc.setText("");
                    this.txtResd.setText("");
                        this.txtRese.setText("");
                            this.txtResf.setText("");
                                this.txtResg.setText("");
                                
        
                
        rbFase1.setSelected(false);
            rbFase2.setSelected(false);
                rbFase3.setSelected(false);
                getContentPane().setBackground(new Color(204 , 204, 204));
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtBeginstandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBeginstandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBeginstandActionPerformed

    private void txtVerbruikPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtVerbruikPropertyChange
        // TODO add your handling code here:
        txtVerbruik.setEditable(false);
    }//GEN-LAST:event_txtVerbruikPropertyChange

    private void txtSaldoaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtSaldoaPropertyChange
        // TODO add your handling code here:
        txtSaldoa.setEditable(false);
    }//GEN-LAST:event_txtSaldoaPropertyChange

    private void txtSaldobPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtSaldobPropertyChange
        // TODO add your handling code here:
        txtSaldob.setEditable(false);
    }//GEN-LAST:event_txtSaldobPropertyChange

    private void txtSaldocPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtSaldocPropertyChange
        // TODO add your handling code here:
        txtSaldoc.setEditable(false);
    }//GEN-LAST:event_txtSaldocPropertyChange

    private void txtSaldodPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtSaldodPropertyChange
        // TODO add your handling code here:
        txtSaldod.setEditable(false);
    }//GEN-LAST:event_txtSaldodPropertyChange

    private void txtSaldoePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtSaldoePropertyChange
        // TODO add your handling code here:
        txtSaldoe.setEditable(false);
    }//GEN-LAST:event_txtSaldoePropertyChange

    private void txtSaldofPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtSaldofPropertyChange
        // TODO add your handling code here:
        txtSaldof.setEditable(false);
    }//GEN-LAST:event_txtSaldofPropertyChange

    private void txtSaldogPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtSaldogPropertyChange
        // TODO add your handling code here:
        txtSaldog.setEditable(false);
    }//GEN-LAST:event_txtSaldogPropertyChange

    private void txtResaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtResaPropertyChange
        // TODO add your handling code here:
        txtResa.setEditable(false);
    }//GEN-LAST:event_txtResaPropertyChange

    private void txtResbPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtResbPropertyChange
        // TODO add your handling code here:
         txtResb.setEditable(false);
    }//GEN-LAST:event_txtResbPropertyChange

    private void txtRescPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtRescPropertyChange
        // TODO add your handling code here:
         txtResc.setEditable(false);
    }//GEN-LAST:event_txtRescPropertyChange

    private void txtResdPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtResdPropertyChange
        // TODO add your handling code here:
         txtResd.setEditable(false);
    }//GEN-LAST:event_txtResdPropertyChange

    private void txtResePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtResePropertyChange
        // TODO add your handling code here:
         txtRese.setEditable(false);
    }//GEN-LAST:event_txtResePropertyChange

    private void txtResfPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtResfPropertyChange
        // TODO add your handling code here:
         txtResf.setEditable(false);
    }//GEN-LAST:event_txtResfPropertyChange

    private void txtResgPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtResgPropertyChange
        // TODO add your handling code here:
         txtResg.setEditable(false);
    }//GEN-LAST:event_txtResgPropertyChange

    private void txtTotaalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtTotaalPropertyChange
        // TODO add your handling code here:
         txtTotaal.setEditable(false);
    }//GEN-LAST:event_txtTotaalPropertyChange

    private void txtFasePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtFasePropertyChange
        // TODO add your handling code here:
         txtFase.setEditable(false);
    }//GEN-LAST:event_txtFasePropertyChange

    private void txtRekeningPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtRekeningPropertyChange
        // TODO add your handling code here:
         txtRekening.setEditable(false);
    }//GEN-LAST:event_txtRekeningPropertyChange

    private void btninstructieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninstructieActionPerformed
        // TODO add your handling code here:
        Instructie s = new Instructie();
        s.setVisible(true);
    }//GEN-LAST:event_btninstructieActionPerformed

    private void txtSaldoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaldoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaldoaActionPerformed

    private void txtTotaalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotaalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotaalActionPerformed

    private void txtBeginstandKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBeginstandKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
    if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE)){
    getToolkit().beep();
        evt.consume();
    }
    }//GEN-LAST:event_txtBeginstandKeyTyped

    private void txtEindstandKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEindstandKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
    if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE)){
    getToolkit().beep();
        evt.consume();
    }
    }//GEN-LAST:event_txtEindstandKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Verbruikerscalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Verbruikerscalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Verbruikerscalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Verbruikerscalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            try
            {
                Thread.sleep(2500);
            }
         catch(Exception e)
         {
             
         }
            
          new Verbruikerscalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBereken;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btninstructie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblBeginstand;
    private javax.swing.JLabel lblEindstand;
    private javax.swing.JLabel lblFase;
    private javax.swing.JLabel lblRekening;
    private javax.swing.JLabel lblTotaal;
    private javax.swing.JLabel lblVerbruik;
    private javax.swing.JRadioButton rbFase1;
    private javax.swing.JRadioButton rbFase2;
    private javax.swing.JRadioButton rbFase3;
    private javax.swing.JTextField txtBeginstand;
    private javax.swing.JTextField txtEindstand;
    private javax.swing.JTextField txtFase;
    private javax.swing.JTextField txtRekening;
    private javax.swing.JTextField txtResa;
    private javax.swing.JTextField txtResb;
    private javax.swing.JTextField txtResc;
    private javax.swing.JTextField txtResd;
    private javax.swing.JTextField txtRese;
    private javax.swing.JTextField txtResf;
    private javax.swing.JTextField txtResg;
    private javax.swing.JTextField txtSaldoa;
    private javax.swing.JTextField txtSaldob;
    private javax.swing.JTextField txtSaldoc;
    private javax.swing.JTextField txtSaldod;
    private javax.swing.JTextField txtSaldoe;
    private javax.swing.JTextField txtSaldof;
    private javax.swing.JTextField txtSaldog;
    private javax.swing.JTextField txtTotaal;
    private javax.swing.JTextField txtVerbruik;
    // End of variables declaration//GEN-END:variables
}
